"""Guard against the embedded narration-recovery command drifting from the real one.

The self-driving bundle's CLAUDE.md/AGENTS.md (generated by extension/src/bundle-docs.js)
tell a recipient WITHOUT this repo how to recover narration from video.webm. That command
must stay runnable — it once shipped missing `--output-path`, which fails on first run. The
authoritative invocation is analyze/transcribe.py. This asserts the documented command
carries the same required flags + model id, so the two can't silently diverge again.
"""
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = (ROOT / "extension" / "src" / "bundle-docs.js").read_text(encoding="utf-8")
TRANSCRIBE = (ROOT / "analyze" / "transcribe.py").read_text(encoding="utf-8")


class TestRecoveryCommand(unittest.TestCase):
    def test_transcribe_uses_output_path_and_vtt(self):
        # The real path passes these — they're what the doc must mirror.
        self.assertIn("--output-path", TRANSCRIBE)
        self.assertIn('"--format", "vtt"', TRANSCRIBE)

    def test_doc_command_has_required_output_path(self):
        # The bug that prompted this: the documented mlx command lacked --output-path.
        line = next((l for l in DOCS.splitlines() if "mlx_audio.stt.generate" in l), "")
        self.assertTrue(line, "no mlx_audio.stt.generate command found in bundle-docs.js")
        self.assertIn("--output-path", line)
        self.assertIn("--format vtt", line)

    def test_doc_model_matches_transcribe_default(self):
        m = re.search(r'PARAKEET_DEFAULT\s*=\s*"([^"]+)"', TRANSCRIBE)
        self.assertTrue(m, "PARAKEET_DEFAULT not found in transcribe.py")
        model_id = m.group(1)
        self.assertIn(model_id, DOCS,
                      f"bundle-docs.js recovery command must use the same model id ({model_id})")


if __name__ == "__main__":
    unittest.main()
